### ISSUE TITLE
Add reasonable text in place of Lorem ipsum 

### ISSUE THREAD

**Issue by Chetana16032002** [Chetana16032002/Food-blog#1]
In place of lorem Ipsum of food-blog site add reasonable text and cool thoughts about cuisines, good grammar is appreciated .
![image](https://user-images.githubusercontent.com/91176005/135790471-288284bd-3371-4646-a32b-6bb183f65f4e.png)
![image](https://user-images.githubusercontent.com/91176005/135790484-e8f73ba5-bb6c-4000-b23a-002da6741ca2.png)
here I have used the same name(Italian source mushroom) for all the cuisines please find the names for these cuisines and give them accordingly

**Comment by vishnuramv** [comment]
Hey I'm a Hacktoberfest participant, can you assign this issue to me?

**Comment by Hussain6** [comment]
Can you assign this to me?

**Comment by Chetana16032002** [comment]
@vishnuramv you can work on renaming the different cuisines 🤗
![image](https://user-images.githubusercontent.com/91176005/135792831-65e01090-a4cc-478b-902c-3e3a3ca104b8.png)
here I have used the same name(Italian source mushroom) for all the cuisines please find the names for these cuisines and give them accordingly

**Comment by Chetana16032002** [comment]
@Hussain6 you can work on the lorem ipsum 🤗 good grammar is highly appreciated

**Comment by Chetana16032002** [comment]
@vishnuramv @Hussain6 your pull request will  be accepted to hacktoberfest2021 so kindly work on it

**Comment by NarayanBavisetti** [comment]
I also want to contribute, can you assign some task to me.

**Comment by vishnuramv** [comment]
> @vishnuramv @Hussain6 your pull request will be accepted to hacktoberfest2021 so kindly work on it

I sorry I don't know those dish name. You can assign it someone else.

**Comment by Chetana16032002** [comment]
@vishnuramv you can work on lorem ipsum try to add at least some similar cuisine names that won't be an issue 🤗

**Comment by Chetana16032002** [comment]
@NarayanBavisetti  you can work on lorem ipsum and cuisine names 🤗

**Comment by Chetana16032002** [comment]
I will merge all of your pull requests @vishnuramv @Hussain6 @NarayanBavisetti even some contribution is highly appreciated, and be accepted to hacktoberfest

**Comment by passionlord** [comment]
i would like to contribute this 😊

**Comment by Chetana16032002** [comment]
@passionlord sure please add cuisine names, reasonable info in place of lorem ipsum

**Comment by vishnuramv** [comment]
> @vishnuramv you can work on lorem ipsum try to add at least some similar cuisine names that won't be an issue hugs

#4 I replaced the lorem ipsum. see if it's okay.

**Comment by passionlord** [comment]
![participation](https://user-images.githubusercontent.com/62416874/135809354-77a8b85a-caa4-4dad-8518-3e3732f2f032.PNG)


@Chetana16032002 after merging pull request in hacktoberfest page its showing this project is not participating. 😥

**Comment by Chetana16032002** [comment]
@passionlord please wait i am working on it :)
